In [ ]:
#modified code from down 

In [16]:
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from nltk.stem import WordNetLemmatizer
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


# Load the Twitter dataset
data = pd.read_csv("twitter_new.csv", encoding="ISO-8859-1")
data.columns = ["target", "ids", "date", "flag", "user", "text"]

# Data Preprocessing
stop_words = set(stopwords.words("english"))

# remove the plural form
lemmatizer= WordNetLemmatizer()

def preprocess_text(text):
    # Remove special characters, numbers, and extra spaces
    text = " ".join(text.split())
    text = " ".join([word for word in text.split() if word.isalpha()]) 
    # Remove stopwords and convert to lowercase
    text = " ".join([word.lower() for word in text.split() if word not in stop_words])
    text = " ".join([lemmatizer.lemmatize(word) for word in text.split()])
    #token = lemmatizer.lemmatize(token)
    return text

data["text"] = data["text"].apply(preprocess_text)

# Feature Extraction using Bag of Words (BoW)
vectorizer = CountVectorizer(max_features=5000) # top 5000 frequent words are selected 
X = vectorizer.fit_transform(data["text"])
y = data["target"]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

#Logistic Regression
Logistic_Regression= LogisticRegression()
Logistic_Regression.fit(X_train, y_train)

# SVM Classifier
svm_classifier = SVC()
svm_classifier.fit(X_train, y_train)

#KNN Classifier
Knn_classifier = KNeighborsClassifier()
Knn_classifier.fit(X_train, y_train)

#Decision Tree
DecisionTree_classifier = DecisionTreeClassifier(criterion='entropy',max_depth=100)
DecisionTree_classifier.fit(X_train, y_train)


# Random Forest Classifier
rf_classifier = RandomForestClassifier(n_estimators=100, random_state=42)
rf_classifier.fit(X_train, y_train)

#  Adaboost Classifier
Ab_classifier = AdaBoostClassifier()
Ab_classifier.fit(X_train, y_train)

# Gradinet boost Classifier
Gb_classifier = GradientBoostingClassifier()
Gb_classifier.fit(X_train, y_train)



# Evaluate the models
def evaluate_model(model, X_test, y_test):
    y_pred = model.predict(X_test)
    accuracy = accuracy_score(y_test, y_pred)
    conf_matrix = confusion_matrix(y_test, y_pred)
    class_report = classification_report(y_test, y_pred)
    return accuracy, conf_matrix, class_report

lr_accuracy, lr_conf_matrix, lr_class_report = evaluate_model(Logistic_Regression, X_test, y_test)
svm_accuracy, svm_conf_matrix, svm_class_report = evaluate_model(svm_classifier, X_test, y_test)
knn_accuracy, knn_conf_matrix, knn_class_report = evaluate_model(Knn_classifier, X_test, y_test)
decision_tree_accuracy, decision_tree_conf_matrix,decision_tree_class_report = evaluate_model(DecisionTree_classifier, X_test, y_test)
rf_accuracy, rf_conf_matrix, rf_class_report = evaluate_model(rf_classifier, X_test, y_test)
ab_accuracy, ab_conf_matrix, ab_class_report = evaluate_model(Ab_classifier, X_test, y_test)
gb_accuracy, gb_conf_matrix, gb_class_report = evaluate_model(Gb_classifier, X_test, y_test)


print("Logistic Regression Model:")
print("Accuracy:", lr_accuracy)
print("Confusion Matrix:\n", lr_conf_matrix)
print("Classification Report:\n", lr_class_report)

print("SVM Model:")
print("Accuracy:", svm_accuracy)
print("Confusion Matrix:\n", svm_conf_matrix)
print("Classification Report:\n", svm_class_report)

print("KNN Model:")
print("Accuracy:", knn_accuracy)
print("Confusion Matrix:\n", knn_conf_matrix)
print("Classification Report:\n", knn_class_report)

print("Decision Tree Model:")
print("Accuracy:", decision_tree_accuracy)
print("Confusion Matrix:\n", decision_tree_conf_matrix)
print("Classification Report:\n", decision_tree_class_report)


print("\nRandom Forest Model:")
print("Accuracy:", rf_accuracy)
print("Confusion Matrix:\n", rf_conf_matrix)
print("Classification Report:\n", rf_class_report)

print("\n Adaboost Forest Model:")
print("Accuracy:", ab_accuracy)
print("Confusion Matrix:\n", ab_conf_matrix)
print("Classification Report:\n", ab_class_report)

print("\nGradient Forest Model:")
print("Accuracy:", gb_accuracy)
print("Confusion Matrix:\n", gb_conf_matrix)
print("Classification Report:\n", gb_class_report)


Logistic Regression Model:
Accuracy: 0.5238095238095238
Confusion Matrix:
 [[4 9]
 [1 7]]
Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.31      0.44        13
           4       0.44      0.88      0.58         8

    accuracy                           0.52        21
   macro avg       0.62      0.59      0.51        21
weighted avg       0.66      0.52      0.50        21

SVM Model:
Accuracy: 0.42857142857142855
Confusion Matrix:
 [[ 1 12]
 [ 0  8]]
Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.08      0.14        13
           4       0.40      1.00      0.57         8

    accuracy                           0.43        21
   macro avg       0.70      0.54      0.36        21
weighted avg       0.77      0.43      0.31        21

KNN Model:
Accuracy: 0.6666666666666666
Confusion Matrix:
 [[7 6]
 [1 7]]
Classification Report:
               precision    reca

In [ ]:
# code ends 
# Knn has hihgest accuracy in predicting sentiments 

In [ ]:
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the Twitter dataset
data = pd.read_csv("path_to_dataset.csv", encoding="ISO-8859-1")
data.columns = ["target", "ids", "date", "flag", "user", "text"]

# Data Preprocessing
stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    # Remove special characters, numbers, and extra spaces
    text = " ".join(text.split())
    text = " ".join([word for word in text.split() if word.isalpha()]) 
    # Remove stopwords and convert to lowercase
    text = " ".join([word.lower() for word in text.split() if word not in stop_words])
    return text

data["text"] = data["text"].apply(preprocess_text)

# Feature Extraction using Bag of Words (BoW)
vectorizer = CountVectorizer(max_features=5000)
X = vectorizer.fit_transform(data["text"])
y = data["target"]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a classification model (Random Forest)
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Evaluate the model
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)


In [6]:
import pandas as pd
df = pd.read_csv("twitter_new.csv", encoding="ISO-8859-1")
df.columns = ["target", "ids", "date", "flag", "user", "text"]
rows_with_target_0 = df[df['target'] == 0]
rows_with_target_4 = df[df['target'] == 4]

In [7]:
distinct_values = df['target'].unique()

print(distinct_values)

[0 4]


In [8]:
df1=rows_with_target_0.loc[0:50]
df2 =rows_with_target_4.loc[799999:800050]
combined_df = pd.concat([df1, df2], ignore_index=True)

In [9]:
combined_df

target         ids                          date      flag   
0         0  1467810672  Mon Apr 06 22:19:49 PDT 2009  NO_QUERY  \
1         0  1467810917  Mon Apr 06 22:19:53 PDT 2009  NO_QUERY   
2         0  1467811184  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
3         0  1467811193  Mon Apr 06 22:19:57 PDT 2009  NO_QUERY   
4         0  1467811372  Mon Apr 06 22:20:00 PDT 2009  NO_QUERY   
..      ...         ...                           ...       ...   
98        4  1467824377  Mon Apr 06 22:23:18 PDT 2009  NO_QUERY   
99        4  1467824422  Mon Apr 06 22:23:19 PDT 2009  NO_QUERY   
100       4  1467824454  Mon Apr 06 22:23:20 PDT 2009  NO_QUERY   
101       4  1467824474  Mon Apr 06 22:23:20 PDT 2009  NO_QUERY   
102       4  1467824495  Mon Apr 06 22:23:20 PDT 2009  NO_QUERY   

              user                                               text  
0    scotthamilton  is upset that he can't update his Facebook by ...  
1         mattycus  @Kenichan I dived many times for the ball. Man...  
2          ElleCTF    my whole body feels itchy and like its on fire   
3           Karoli  @nationwideclass no, it's not behaving at all....  
4         joy_wolf                      @Kwesidei not the whole crew   
..             ...                                                ...  
98          Toyia1                                        I am bored   
99        deeper2k  @stevecla it is a wallpaper with Red Square I ...  
100      vmdavinci  @r_keith_hill Thanks for your response. Ihad a...  
101       Missy_BB  @Pope_Mello Well yeah! I only noticed cuz i'm ...  
102          EmCDL                 Just tryna get inspired thats all   

[103 rows x 6 columns]

In [10]:
combined_df.to_csv('output.csv', index=False)

In [ ]:
import numpy as np
import pandas as pd
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Load the Twitter dataset
data = pd.read_csv("output.csv", encoding="ISO-8859-1")
data.columns = ["target", "ids", "date", "flag", "user", "text"]

#data = data.loc[0:1000000]
# Data Preprocessing
stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    # Remove special characters, numbers, and extra spaces
    text = " ".join(text.split())
    text = " ".join([word for word in text.split() if word.isalpha()]) 
    # Remove stopwords and convert to lowercase
    text = " ".join([word.lower() for word in text.split() if word not in stop_words])
    return text

data["text"] = data["text"].apply(preprocess_text)

# Feature Extraction using Bag of Words (BoW)
vectorizer = CountVectorizer(max_features=5000)
X = vectorizer.fit_transform(data["text"])
y = data["target"]

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train a classification model (Random Forest)
clf = RandomForestClassifier(n_estimators=100, random_state=42)
clf.fit(X_train, y_train)

# Evaluate the model
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Accuracy:", accuracy)
print("Confusion Matrix:\n", conf_matrix)
print("Classification Report:\n", class_report)
